apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loadbalancer
subjects:
  - kind: ServiceAccount
    name: sa-loadbalancer
roleRef:
  kind: Role
  name: loadbalancer
  apiGroup: rbac.authorization.k8s.io